export const mobileAuthPage = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src https://cdn.jsdelivr.net 'unsafe-inline'; connect-src https://studio-api.nxcode.io; style-src 'unsafe-inline'; img-src https: data:; frame-src https:;">
<title>Connect AIopter</title><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;background:radial-gradient(circle at 50% 20%,#123465,#080b12 50%);font:16px system-ui;color:#eef7ff}.card{width:min(90vw,420px);padding:34px;border:1px solid #315b84;border-radius:28px;background:#0e1724e8;box-shadow:0 24px 80px #0008;text-align:center}.logo{font-size:48px;color:#54dcff;text-shadow:0 0 24px #2b8cff}.tag{color:#7e9ab8;font-size:12px;letter-spacing:2px}button{width:100%;padding:15px;margin-top:24px;border:0;border-radius:14px;background:linear-gradient(135deg,#48d7ff,#326bff);font-weight:750;color:#06101c;font-size:16px}button:disabled{opacity:.55}.note{color:#9db0c3;font-size:13px;line-height:1.5}.error{color:#ff9ea8;min-height:22px}</style></head>
<body><main class="card"><div class="logo">◉</div><h1>Connect AIopter</h1><p class="tag">SEE. ASK. DO. ANYWHERE</p><p class="note">Sign in securely with Nxcode. AIopter receives a session token, never your password.</p><button id="login">Continue securely</button><p id="status" class="error"></p></main>
<script src="https://cdn.jsdelivr.net/npm/@nxcode/sdk@1.0.14/dist/nxcode.min.js"></script><script>
const button=document.getElementById('login'),status=document.getElementById('status');
button.onclick=async()=>{button.disabled=true;status.textContent='Opening secure sign-in…';try{await Nxcode.ready();const user=await Nxcode.auth.login();const token=Nxcode.auth.getToken();if(!token)throw new Error('No session returned');if(!window.AIopterAuth)throw new Error('Open this page inside the AIopter app');window.AIopterAuth.complete(JSON.stringify({token,user:{id:user.id,name:user.name,email:user.email}}));status.textContent='Connected. Returning to AIopter…'}catch(e){status.textContent=e.message||'Sign-in did not complete';button.disabled=false}};
</script></body></html>`
